### PR TITLE
WIP: include filename in stache() call

### PR DESCRIPTION
**Pull request by christopherjbaker**
reminder: bump can-stache dependecy

### CODE REVIEW

**Review by phillipskevin — CHANGES_REQUESTED** [review]
Can you add a test?

**Comment by christopherjbaker** [comment]
Other than creating a stache that has a parsing error and making sure the error has the filename, any suggestions on how to test this? Do we have a simplish way to mock the `require('stache')`?

**Comment by phillipskevin** [comment]
You can use `steal-clone`. Something like this should work:

```
	function fakeStache() {
		// check that the filename is passed
	}

	clone({
		'can-stache': {
			default: fakeStache
		}
	})
	.import('test/tests/foo.stache')
	.then(...);
```

**Review by phillipskevin — APPROVED** [review]

**Review by phillipskevin — CHANGES_REQUESTED** [review]
unnapproving until `can-stache` is published.

**Review by phillipskevin — APPROVED** [review]
approving assuming you update the stache dependency.

**Pull request merged**
